In [5]:
import numpy as np
import tensorflow as tf

In [3]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\borja\\anaconda3\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [8]:
#Rank/Degree of Tensors

rank1_tensor = tf.Variable(["Test"],tf.string) #rank 1, it has an array
rank2_tensor = tf.Variable([["Test1","Test2"],["ok","ok2"]],tf.string) #rank 2, it has 2 arrays

tf.rank(rank1_tensor)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [11]:
#Reshaping tensors
tensor1 = tf.ones([1,2,3]) #It creates a tensor of 1s

tensor2 = tf.reshape(tensor1,[2,3,1])
tensor3 = tf.reshape(tensor1,[3,-1]) #-1 tells to tensor to calculate the size
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
#Evaluating Tensors

with tf.Session() as sess:
    tensor.eval()